CREATE TABLE COMPANY (
    COMPANY_ID	INT  NOT NULL   auto_increment  PRIMARY KEY,
    COMPANY_NAME  VARCHAR(100)  NOT NULL UNIQUE,
    COMPANY_COUNTRY  VARCHAR(30)  NOT NULL,
    COMPANY_AREA  VARCHAR(30)  NOT NULL
);

CREATE TABLE EMPLOY (
    EMPLOY_ID	INT  NOT NULL  auto_increment  PRIMARY KEY,
    COMPANY_ID	INT  NOT NULL,
    EMPLOY_POSITION	VARCHAR(100)  NOT NULL,
    EMPLOY_MONEY_GIFT	INT  NOT NULL,
    EMPLOY_CONTENT	TEXT(2000)  NOT NULL,
    EMPLOY_SKILL	VARCHAR(30)  NOT NULL
);

CREATE TABLE USER (
    USER_ID	 VARCHAR(30)  NOT NULL,
    USER_NAME	VARCHAR(30)  NOT NULL,
    USER_AREA	VARCHAR(30)	NOT NULL,
    USER_SKILL	VARCHAR(30)	NOT NULL,
    USER_POSITION	VARCHAR(100)	 NOT NULL
);

CREATE TABLE APPLY (
    APPLY_ID	INT	NOT NULL  auto_increment  PRIMARY KEY,
    EMPLOY_ID	INT	NOT NULL,
    USER_ID	VARCHAR(30)	NOT NULL
);

